### ISSUE TITLE
unexpected ']'

### ISSUE THREAD

**Issue by jhaleit** [paszin/alexa-soundcloud#1]
Can't save due to code error on line 34. "unexpected ']'"

**Comment by paszin** [comment]
Hi @jhaleit,

thanks for reporting the error. But unfortunately I can't reproduce the error. What are the steps to get to the exception?

**Comment by tweedyf** [comment]
@paszin @jhaleit there's a `,` that shouldn't be there on line 53 of interactionModel_en.json -- if you remove it the error will go away

**Comment by eversonl** [comment]
would love to get this working but am getting stuck with the logs showing : Unable to import module 'lambda': No module named lambda..  I have tried changing the handler to match the python filename of skill but that does not help. Can anyone assist?

**Comment by paszin** [comment]
thanks @tweedy7736
